export const CommonErrorCode = {
  BAD_REQUEST: 'COMMON.BAD_REQUEST',
  VALIDATION_FAILED: 'COMMON.VALIDATION_FAILED',
  UNAUTHORIZED: 'COMMON.UNAUTHORIZED',
  FORBIDDEN: 'COMMON.FORBIDDEN',
  NOT_FOUND: 'COMMON.NOT_FOUND',
  CONFLICT: 'COMMON.CONFLICT',
  TOO_MANY_REQUESTS: 'COMMON.TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE: 'COMMON.SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'COMMON.INTERNAL_ERROR',
} as const;

export type CommonErrorCode = (typeof CommonErrorCode)[keyof typeof CommonErrorCode];
